### ISSUE TITLE
Jobs page crashes on fresh mcritweb install

### ISSUE THREAD

**Issue by yankovs** [fkie-cad/mcritweb#17]
Hey!

When using a fresh docker-mcrit instance with no jobs, rendering `jobs.html` crashes and the user sees an internal server error.  
This is because in such cases, `active_category == None` and so `menu_configuration == {}`. Jinja2 then tries to access `menu_configuration[statistics]` and you get a crashed page.

To reproduce:  
* cd storage
* remove mcritweb and mongodb directories
* Sign up and visit the jobs page

I suggest two ways to solve this:  
* Initialize `menu_configuration` as `menu_configuration = {"statistics": statistics}`. This will make it not crash but the Jobs page will not be as pretty looking in case you enter with a fresh install
* Like the one above, but also include an initial `menu` key in it with everything disabled but still there, just so the user sees all the toggles

**Comment by danielplohmann** [comment]
Haha, seems like I was too concerned with ensuring that it works and shows the info nicely when jobs are available. ;) 
Thanks you very much for the PR, will integrate asap and push a new release.
